packaging_format = 2

id = "mlmmj-simple-web"
name = "Mlmmj Simple Web Interface"
description.en = "A simple web frontend for mlmmj mailing list management."
description.fr = "Une interface web simple pour la gestion des listes de diffusion mlmmj."

version = "1.0~ynh1"

maintainers = ["VotreNomUtilisateur"]

[upstream]
license = "MIT"
website = "https://github.com/ashledombos/mlmmj-simple-web-interface"
code = "https://github.com/ashledombos/mlmmj-simple-web-interface"
admindoc = "https://github.com/ashledombos/mlmmj-simple-web-interface"
userdoc = "https://github.com/ashledombos/mlmmj-simple-web-interface"

[integration]
yunohost = ">= 11.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "10M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mlmmj"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    ask.en = "Choose the administrator user for this application:"
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ["nodejs", "npm", "autres dépendances nécessaires"]

    [resources.sources.main]
    url = "https://github.com/ashledombos/mlmmj-simple-web-interface/archive/master.tar.gz"
    sha256 = "sha256sumDuFichierSource"
    autoupdate.strategy = "latest_github_release"

