packaging_format = 2

id = "mlmmj-web"
name = "Mlmmj Web"
description.en = "Simple web frontend for mlmmj mailing list management"
description.fr = "Interface web simple pour la gestion des listes de diffusion mlmmj"

version = "0.0.1~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "http://mlmmj.org"
code = "https://github.com/ashledombos/mlmmj-simple-web-interface"

[integration]
yunohost = ">= 11.2.28"
architectures = "all"
multi_instance = false
ldap = false
sso = false

disk = "10M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/ashledombos/mlmmj-simple-web-interface/archive/refs/tags/test.tar.gz"
    sha256 = "bcc09a7a573f84f8f15d82306a1cc5430ae6b6c440221a92ba7d4a92174f09bd"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
