#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gestionliste"
name = "Gestion Liste"
description.en = "A bespoke web page for managing lists with PHP scripts and group-based access control"
description.fr = "Une page web sur mesure pour gérer des listes avec des scripts PHP et un contrôle d'accès basé sur les groupes"

version = "1.0~ynh1"

maintainers = ["ashledombos"]

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "10M"
ram.build = "10M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mlmmj_web"

    [install.init_main_permission]
    type = "group"
    default = "visitors"  

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]

    [resources.system_user]
    [resources.install_dir]
    [resources.data_dir]
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    [resources.apt]
    packages = "php8.0"

    [resources.custom]
    # fichier de gestion des droits en YAML, je suppose
