#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    preinstall = """
    sudo yunohost app install mlmmj -a "&list_email=list@domain.tld&owner=package_checker"
    """
