#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
#path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
#is_public=$YNH_APP_ARG_IS_PUBLIC

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..."

ynh_install_nodejs --nodejs_version="14"
ynh_use_nodejs

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" 

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"
ynh_exec_as $app npm install --prefix $install_dir
#ynh_exec_as $app npm audit fix --prefix $install_dir

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# CREATE A SYSTEM USER
#=================================================
#ynh_script_progression --message="Creating a system user..."

# Create a system user
#ynh_system_user_create --username=$app

#=================================================
# GIVE ACCESS TO MLMMJ
#=================================================
ynh_script_progression --message="Givinh access to MLMMJ;"

setfacl -R -m u:$app:rwx /var/spool/mlmmj/files
setfacl -m d:$app:rwx /var/spool/mlmmj/files

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a config file..."

# Create a config file
ynh_add_config --template="config.json" --destination="$install_dir/config.json"

chmod 400 "$install_dir/config.json"
chown $app:$app "$install_dir/config.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."


# Create a systemd service

ynh_add_systemd_config
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
